@startuml HNcancelEnteredInError

'layout
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
  }
hide circle
hide empty members
skinparam SameClassWidth true
skinparam Ranksep 10


'title
title Simplified example: Cancellation Start hospital stay - admitted

'Message 1: Admit inpatient
package "Cancellation Start hospital stay - admitted" as cancel <<Frame>>{
    class "Bundle (MedComHospitalNotificationMessage)" as cancelB{
        id = "c83671a4-9584-11ec-b909-0242ac120002"
        type = "message"
        timestamp = "2022-12-07T15:00:01+02:00"
    }
    class "MessageHeader (MedComHospitalNotificationMessageHeader)" as cancelMH{
        id = "d8749b54-1aeb-4089-8941-8d876bdffc51"
        event.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-eventCodes"
        event.code = "hospital-notification-message"
        destination.use.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-destinationUse"
        destination.use.code = "primary"
        destination.endpoint = "https://sor2.sum.dsdn.dk/#id=953741000016009"
        destination.receiver.reference = "Organization/eefc2dfa-81c6-11ed-a1eb-0242ac120002"
        sender.reference = "Organization/05266a00-81c7-11ed-a1eb-0242ac120002"
        source.endpoint = "https://sor2.sum.dsdn.dk/#id=265161000016000"
        focus = "Encounter/c9782061-ce63-41b5-8be6-655812d23332"
    }
    class "Patient (MedComCorePatient)" as cancelPT{
        id = "d6eeaca6-81c6-11ed-a1eb-0242ac120002"
        identifier.system = "urn:oid:1.2.208.176.1.2"
        identifier.value = "2509479989"
        name.use = "official"
        name.family = "Elmer"
        name.given[0] = "Bruno"
        name.given[1] = "Test"
    }
    class "Encounter (MedComHospitalNotificationEncounter)" as cancelENC{
        id = "c9782061-ce63-41b5-8be6-655812d23332"
        status.system = "http://medcomfhir.dk/ig/terminology/ValueSet/medcom-hospitalNotification-encounterStatus"
        status.code = "entered-in-error"
        class.system = "http://terminology.hl7.org/CodeSystem/v3-ActCode"
        class.code = "IMP"
        subject = "Patient/d6eeaca6-81c6-11ed-a1eb-0242ac120002"
        episodeOfCare.identifier.system = "https://www.esundhed.dk/Registre/Landspatientsregisteret"
        episodeOfCare.identifier.value = "urn:uuid:fc60e762-b13b-5773-865e-67f3907bdcc7"
        period.start = "2022-12-07T12:00:00+02:00"
        serviceProvider = "Organization/05266a00-81c7-11ed-a1eb-0242ac120002"
    }    
    class "Receiver (MedComMessagingOrganization)" as cancelROrg{
        id = "eefc2dfa-81c6-11ed-a1eb-0242ac120002"
        identifier[0].system = "https://www.gs1.org/gln"
        identifier[0].value = "5790001348120"
        identifier[1].system = "urn:oid:1.2.208.176.1.1"
        identifier[1].value = "953741000016009"
        name = "Plejecenter Herlev"
    }
    class "Sender (MedComMessagingOrganization)" as cancelSOrg{
        id = "05266a00-81c7-11ed-a1eb-0242ac120002"
        identifier[0].system = "https://www.gs1.org/gln"
        identifier[0].value = "5790000209354"
        identifier[1].system = "urn:oid:1.2.208.176.1.1"
        identifier[1].value = "265161000016000"
        name = "Hjerteafdelingen på Herlev og Gentofte hospital" 
    }
    class "Provenance (MedComMessagingProvenance)" as admitPRO{
        id = "a7cf3888-6f42-4e4d-929c-d2475d24fba0"
        target = "MessageHeader/b9b4818e-02de-4cc4-b418-d20cbc7b5404"
        occuredDateTime = "2022-12-07T12:00:02+02:00"
        recorded = "2022-12-07T12:00:02+02:00"
        activity.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-activityCodes"
        activity.code = "admit-inpatient"
        agent.who = "Organization/d6ed6725-1aec-42ad-829d-f7074c3914f3"
    }
    class "Provenance (MedComMessagingProvenance)" as cancelPRO{
        id = "c67ecb1c-957a-11ec-b909-0242ac120002"
        target = "MessageHeader/d8749b54-1aeb-4089-8941-8d876bdffc51"
        occuredDateTime = "2022-12-07T15:00:02+02:00"
        recorded = "2022-12-07T15:00:02+02:00"
        activity.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-activityCodes"
        activity.code = "cancel-admit-inpatient"
        agent.who = "Organization/05266a00-81c7-11ed-a1eb-0242ac120002"
        entity.role.system = "http://hl7.org/fhir/ValueSet/provenance-entity-role"
        entity.role.value = "removal"
        entity.what = "MessageHeader/b9b4818e-02de-4cc4-b418-d20cbc7b5404"
    }

cancelB -[hidden]- cancelMH
cancelMH-[hidden]-cancelPT
cancelPT-[hidden]-cancelENC
cancelENC-[hidden]-cancelROrg
cancelROrg-[hidden]-cancelSOrg
cancelSOrg-[hidden]-admitPRO
admitPRO-[hidden]-cancelPRO
}

@enduml

