@startuml HNAdmitOnleaveEndFinish

'layout
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
  }
hide circle
hide empty members
skinparam SameClassWidth true
skinparam Ranksep 10


'title
title Simplified example: Admit, Onleave, and Discharge Inpatient


package "Message 1: Admit Inpatient" as admit <<Frame>>{
    class "Bundle (MedComHospitalNotificationMessage)" as admitB{
        id = BUN1
        type = "message"
        timestamp = 2021-12-01T12:00:10+01:00
    }
    class "MessageHeader (MedComHospitalNotificationMessageHeader)" as admitMH{
        id = MH1
        event = "hospital-notification-message"
        destination:primary = MedComMessagingOrganization/RO1
        destination:primary.use = "primary"
        destination:primary.endpoint = *url to receiver of HospitalNotification message*
        sender = MedComMessagingOrganization/SO1
        source.endpoint = *url to receiver of Acknowledgement*
        focus = MedComHospitalNotificationEncounter/ENC1
    }
    class "Patient (MedComCorePatient)" as admitPT{
        id = PA1
        identifier:cpr = 2509479989
        name.family = Elmer
        name.given[0] = Bruno
        name.given[1] = Test
    }
    class "Encounter (MedComHospitalNotificationEncounter)" as admitENC{
        id = ENC1
        status = "in-progress"
        class = "IMP"
        subject = MedComCorePatient/PA1
        episodeOfCare = *refence to the episode of care*
        episodeOfCare.identifier = "urn:uuid:fc60e762-b13b-5773-865e-67f3907bdcc7"
        period.start = 2021-12-01T12:00:00+01:00
        serviceProvider = MedComCoreOrganization/SPO1
    }    
    class "ServiceProvider Organization (MedComCoreOrganization)" as admitSPOrg{
        id = SPO1
        sorIdentifier = 369258147
    }
    class "Receiver: Municipality (MedComMessagingOrganization)" as admitROrg{
        id = RO1
        eanIdentifier = 987654321
        sorIdentifier = 741852963
    }
    class "Sender: Hospital (MedComMessagingOrganization)" as admitSOrg{
        id = SO1
        eanIdentifier = 123456789
        sorIdentifier = 369258147
    }
    class "Provenance (MedComMessagingProvenance)" as admitPRO{
        id = PROV2
        target = MH1
        occuredDateTime = 2021-12-01T12:00:10+01:00
        recorded = 2021-12-01T12:00:20
        activity.code = "admit-inpatient"
        agent.who = MedComMessagingOrganization/SO1
    }

admitB -[hidden]- admitMH
admitMH-[hidden]-admitPT
admitPT-[hidden]-admitENC
admitENC-[hidden]-admitSPOrg
admitSPOrg-[hidden]-admitROrg
admitROrg-[hidden]-admitSOrg
admitSOrg-[hidden]-admitPRO
}

'Message 2: Onleave inpatient
package "Message 2: Start Onleave Inpatient" as Onleave <<Frame>> {
    class "Bundle (MedComHospitalNotificationMessage)" as onleaveB {
        id = BUN2
        type = "message"
        timestamp = 2021-12-02T08:00:10
    }
    class "MessageHeader (MedComHospitalNotificationMessageHeader)" as onleaveMH{
        id = MH2
        event = "hospital-notification-message"
        destination:primary = MedComMessagingOrganization/RO1
        destination:primary.use = "primary"
        destination:primary.endpoint = *url to receiver of HospitalNotification message*
        sender = MedComMessagingOrganization/SO1
        source.endpoint = *url to receiver of Acknowledgement*
        focus = MedComHospitalNotificationEncounter/ENC1
    }
    class "Patient (MedComCorePatient)" as onleavePT{
        id = PA1
        identifier:cpr = 2509479989
        name.family = Elmer
        name.given[0] = Bruno
        name.given[1] = Test
    }
    class "Encounter (MedComHospitalNotificationEncounter)" as onleaveENC{
        id = ENC2
        status = "onleave"
        class = "IMP"
        subject = MedComCorePatient/PA1
        episodeOfCare = *refence to the episode of care*
        episodeOfCare.identifier = "urn:uuid:fc60e762-b13b-5773-865e-67f3907bdcc7"
        period.start = 2021-12-01T12:00:00Z
        serviceProvider = MedComCoreOrganization/SPO1
    }
    class "Service Provider Organization (MedComCoreOrganization)" as onleaveSPOrg{
        id = SPO1
        sorIdentifier = 369258147
    }
    class "Receiver: Municipality (MedComMessagingOrganization)" as onleaveROrg{
        id = RO1
        eanIdentifier = 987654321
        sorIdentifier = 741852963
    }
    class "Sender: Hospital (MedComMessagingOrganization)" as onleaveSOrg{
        id = SO1
        eanIdentifier = 123456789
        sorIdentifier = 369258147
    }
    class "Provenance (MedComMessagingProvenance)" as admitonleavePRO{
        id = PROV1
        target = MessageHeader/MH1
        occuredDateTime = 2021-12-01T12:00:10+01:00
        recorded = 2021-12-01T12:00:20
        activity.code = "admit-inpatient"
        agent.who = MedComMessagingOrganization/SO1
    }
    class "Provenance (MedComMessagingProvenance)" as onleavePRO{
        id = PROV2        
        target = MH2
        occuredDateTime = 2021-12-01T12:00:10+01:00
        recorded = 2021-12-01T12:00:20
        activity = "start-leave-inpatient"
        agent.who = MedComMessagingOrganization/SO1
        entity.role = "deriviation"
        entity.what = MessageHeader/MH1

    }
onleaveB-[hidden]-onleaveMH
onleaveMH-[hidden]-onleavePT
onleavePT-[hidden]-onleaveENC
onleaveENC-[hidden]-onleaveSPOrg
onleaveSPOrg-[hidden]-onleaveROrg
onleaveROrg-[hidden]-onleaveSOrg
onleaveSOrg-[hidden]-admitonleavePRO
admitonleavePRO-[hidden]-onleavePRO

}

'Message 3: End onleave inpatient
package "Message 3: End onleave Inpatient" as endOnleave <<Frame>> {
    class "Bundle (MedComHospitalNotificationMessage)" as endOnleaveB {
        id = BUN3
        type = "message"
        timestamp = 2021-12-03T13:00:00
    }
    class "MessageHeader (MedComHospitalNotificationMessageHeader)" as endOnleaveMH{
        id = MH3
        event = "hospital-notification-message"
        destination:primary = MedComMessagingOrganization/RO1
        destination:primary.use = "primary"
        destination:primary.endpoint = *url to receiver of HospitalNotification message*
        sender = MedComMessagingOrganization/SO1
        source.endpoint = *url to receiver of Acknowledgement*
        focus = MedComHospitalNotificationEncounter/ENC1
    }
    class "Patient (MedComCorePatient)" as endOnleavePT{
        id = PA1
        identifier:cpr = 2509479989
        name.family = Elmer
        name.given[0] = Bruno
        name.given[1] = Test
    }
    class "Encounter (MedComHospitalNotificationEncounter)" as endOnleaveENC{
        id = ENC3
        status = "in-progress"
        class = "IMP"
        subject = MedComCorePatient/PA1
        episodeOfCare = *refence to the episode of care*
        episodeOfCare.identifier = "urn:uuid:fc60e762-b13b-5773-865e-67f3907bdcc7"
        period.start = 2021-12-01T12:00:00Z
        serviceProvider = MedComCoreOrganization/SPO1
    }
    class "ServiceProvider Organization (MedComCoreOrganization)" as endOnleaveSPOrg{
        id = SPO1
        sorIdentifier = 369258147
    }
    class "Receiver: Municipality (MedComMessagingOrganization)" as endOnleaveROrg{
        id = RO1
        eanIdentifier = 987654321
        sorIdentifier = 741852963
    }
    class "Sender: Hospital (MedComMessagingOrganization)" as endOnleaveSOrg{
        id = SO1
        eanIdentifier = 123456789
        sorIdentifier = 369258147
    }    
    class "Provenance(MedComMessagingProvenance)" as admitendOnleavePRO{
        id = PROV1
        target = MessageHeader/MH1
        occuredDateTime = 2021-12-01T12:00:10+01:00
        recorded = 2021-12-01T12:00:20
        activity.code = "admit-inpatient"
        agent.who = MedComMessagingOrganization/SO1
    }
    class "Provenance (MedComMessagingProvenance)" as onleaveendOnleavePRO{
        id = PROV2        
        target = MessageHeader/MH2
        occuredDateTime = 2021-12-02T08:00:00+01:00
        recorded = 2021-12-02T08:00:20
        activity = "start-leave-inpatient"
        agent.who = MedComMessagingOrganization/SO1
        entity.role = "deriviation"
        entity.what = MessageHeader/MH1
    }
    class "Provenance (MedComMessagingProvenance)" as endOnleavePRO{
        id = PROV3        
        target = MessageHeader/MH3
        occuredDateTime = 2021-12-03T13:00:00+01:00
        recorded = 2021-12-03T13:00:20
        activity = "end-leave-inpatient"
        agent.who = MedComMessagingOrganization/SO1
        entity.role = "deriviation"
        entity.what = MessageHeader/MH2
    }
endOnleaveB-[hidden]-endOnleaveMH
endOnleaveMH-[hidden]-endOnleavePT
endOnleavePT-[hidden]-endOnleaveENC
endOnleaveENC-[hidden]-endOnleaveSPOrg
endOnleaveSPOrg-[hidden]-endOnleaveROrg
endOnleaveROrg-[hidden]-endOnleaveSOrg
endOnleaveSOrg-[hidden]-admitendOnleavePRO
admitendOnleavePRO-[hidden]-onleaveendOnleavePRO
onleaveendOnleavePRO-[hidden]-endOnleavePRO

}


'Message 2: Finished inpatient
package "Message 4: Discharge Inpatient to Home" as finished <<Frame>>{
    class "Bundle (MedComHospitalNotificationMessage)" as finishedB{
        id = BUN4
        type = "message"
        timestamp = 2021-12-04T14:00:10+01:00
    }
    class "MessageHeader (MedComHospitalNotificationMessageHeader)" as finishedMH{
        id = MHID2
        event = "hospital-notification-message"
        destination:primary = MedComMessagingOrganization/RO2
        destination:primary.use = "primary"
        destination:primary.endpoint = *url to receiver of HospitalNotification message*
        sender = MedComMessagingOrganization/SO1
        source.endpoint = *url to receiver of Acknowledgement*
        focus = MedComHospitalNotificationEncounter/ENC2
    }
    class "Patient (MedComCorePatient)" as finishedPT{
        id = PA1
        identifier:cpr = 2509479989
        name.family = Elmer
        name.given[0] = Bruno
        name.given[1] = Test
    }
    class "Encounter (MedComHospitalNotificationEncounter)" as finishedENC{
        id = ENC4
        status = "finished"
        class = "IMP"
        subject = MedComCorePatient/PA1
        episodeOfCare = *refence to the episode of care*
        episodeOfCare.identifier = "urn:uuid:fc60e762-b13b-5773-865e-67f3907bdcc7"
        period.start = 2021-12-01T12:00:00+01:00
        serviceProvider = MedComCoreOrganization/SPO1
    }
    class "ServiceProvider Organization (MedComCoreOrganization)" as finishedSPOrg{
        id = SPO1 
        sorIdentifier = 369258147
    }    
    class "Receiver: Municipality (MedComMessagingOrganization)" as finishedROrg{
        id = RO1
        eanIdentifier = 987654321
        sorIdentifier = 741852963
    }
    class "Sender: Hospital (MedComMessagingOrganization)" as finishedSOrg{
        id = SO1
        eanIdentifier = 123456789
        sorIdentifier = 369258147
    }    
    class "Provenance (MedComMessagingProvenance)" as admitfinishedPRO{
        id = PROV1
        target = MessageHeader/MH1
        occuredDateTime = 2021-12-01T12:00:10+01:00
        recorded = 2021-12-01T12:00:20
        activity.code = "admit-inpatient"
        agent.who = MedComMessagingOrganization/SO1
    }
    class "Provenance (MedComMessagingProvenance)" as startfinishedPRO{
        id = PROV2        
        target = MessageHeader/MH2
        occuredDateTime = 2021-12-02T08:00:00+01:00
        recorded = 2021-12-02T08:00:20
        activity = "start-leave-inpatient"
        agent.who = MedComMessagingOrganization/SO1
        entity.role = "deriviation"
        entity.what = MessageHeader/MH1
    }
    class "Provenance (MedComMessagingProvenance)" as endfinishedPRO{
        id = PROV3        
        target = MessageHeader/MH3
        occuredDateTime = 2021-12-03T13:00:00+01:00
        recorded = 2021-12-03T13:00:20
        activity = "end-leave-inpatient"
        agent.who = MedComMessagingOrganization/SO1
        entity.role = "deriviation"
        entity.what = MessageHeader/MH2
    }
    class "Provenance (MedComMessagingProvenance)" as finishedPRO{
        id = PROV4
        target = MessageHeader/MH4
        occuredDateTime = 2021-12-04T14:00:10+01:00
        recorded = 2021-12-04T14:00:20
        activity = "discharge-inpatient-home"
        agent.who = MedComMessagingOrganization/SO1
        entity.role = "deriviation"
        entity.what = MessageHeader/MH3
    }
finishedB-[hidden]-finishedMH
finishedMH-[hidden]-finishedPT
finishedPT-[hidden]-finishedENC
finishedENC-[hidden]-finishedSPOrg
finishedSPOrg-[hidden]-finishedROrg
finishedROrg-[hidden]-finishedSOrg
finishedSOrg-[hidden]-admitfinishedPRO
admitfinishedPRO-[hidden]-startfinishedPRO
startfinishedPRO-[hidden]-endfinishedPRO
endfinishedPRO-[hidden]-finishedPRO


}



@enduml

