@startuml HNAdmitFinish

'layout
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
  }
hide circle
hide empty members
skinparam SameClassWidth true
skinparam Ranksep 10


'title
'title Simplified example: Admit and Discharge Inpatient

'Message 2: Finished inpatient
package "Message 2: Discharge Inpatient to Home" as finished <<Frame>>{
    class "Bundle  (MedComHospitalNotificationMessage)" as finishedB{
        id = 20591605-0934-4c8a-926b-3a8178b264ff
        type = "message"
        timestamp = 2022-09-31T09:22:33+02:00
    }
    class "MessageHeader  (MedComHospitalNotificationMessageHeader)" as finishedMH{
        id = 2d766dbc-4cce-4edc-a6d0-b0423bd22b94
        event = "hospital-notification-message"
        destination:primary = Organization
        destination:primary.use = "primary"
        destination:primary.endpoint = https://sor2.sum.dsdn.dk/#id=953741000016009
        sender = Organization
        source.endpoint = https://sor2.sum.dsdn.dk/#id=265161000016000 
        focus = Encounter
    }
    class "Patient  (MedComCorePatient)" as finishedPT{
        id = 2106cd4e-080f-4f7a-b453-57777bfd2220
        identifier:cpr = 2509479989
        name.family = Elmer
        name.given[0] = Bruno
        name.given[1] = Test
    }
    class "Encounter  (MedComHospitalNotificationEncounter)" as finishedENC{
        id = a182d8fa-7f41-42e5-8aa3-49ae228a95ec
        status = "finished"
        class = "IMP"
        subject = Patient
        episodeOfCare.identifier = "urn:uuid:fc60e762-b13b-5773-865e-67f3907bdcc7"
        period.start = 2022-09-01T12:00:05+02:00
        serviceProvider = Organization
    }
    class "ServiceProvider Organization (MedComCoreOrganization)" as finishedSPOrg{
        id = 0bb913be-fae5-4a8c-8229-9dbe9a1ff82a
        sorIdentifier = 265161000016000
    }    
    class "Receiver: Municipality (MedComMessagingOrganization)" as finishedROrg{
        id = a2c7fd20-3456-4417-bdf7-0d6dd0db2e79
        eanIdentifier = 5790001348120
        sorIdentifier = 953741000016009
    }
    class "Sender: Hospital (MedComMessagingOrganization)" as finishedSOrg{
        id = ccc7cae0-b23c-488d-82fb-3dcca55301e3
        eanIdentifier = 5790000209354
        sorIdentifier = 265161000016000
    }    
    class "Provenance (MedComMessagingProvenance)" as admitfinishedPRO{
        id = a7128eb7-8df1-4479-b56f-9c66970159f6
        target = MessageHeader
        occuredDateTime = 2022-09-01T12:00:30+02:00
        recorded = 2022-09-01T12:00:30
        activity.code = "admit-inpatient"
        agent.who = Organization
    }
    class "Provenance (MedComMessagingProvenance)" as finishedPRO{
        id = 8a79ed66-46e5-4642-9565-97036dc06190        
        target = MessageHeader
        occuredDateTime = 2022-09-31T09:22:53+02:00
        recorded = 2022-09-31T09:22:53+02:00
        activity = "discharge-inpatient-home"
        agent.who = Organization
        entity.role = "deriviation"
        entity.what = MessageHeader
    }
finishedB-[hidden]-finishedMH
finishedMH-[hidden]-finishedPT
finishedPT-[hidden]-finishedENC
finishedENC-[hidden]-finishedSPOrg
finishedSPOrg-[hidden]-finishedROrg
finishedROrg-[hidden]-finishedSOrg
finishedSOrg-[hidden]-admitfinishedPRO
admitfinishedPRO-[hidden]-finishedPRO

}

' pile mellem de to beskeder
' admit --> finished


@enduml

