@startuml HNstartOnleave
'layout
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
  }
hide circle
hide empty members
skinparam SameClassWidth true
skinparam Ranksep 10


'title
title Simplified example: Start leave


'Message 3: End onleave inpatient
package "Start leave" as startOnleave <<Frame>> {
    class "Bundle (MedComHospitalNotificationMessage)" as startOnleaveB{
        id = "d3128d9b-cede-4c7f-8904-809eab322d7d"
        type = "message"
        timestamp = "2022-12-13T15:30:01+02:00"
    }
    class "MessageHeader (MedComHospitalNotificationMessageHeader)" as startOnleaveMH{
        id = "e563a2b2-bf92-4b13-bbd2-0a021a95bded"
        event.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-eventCodes"
        event.code = "hospital-notification-message"
        destination.use.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-destinationUse"
        destination.use.code = "primary"
        destination.endpoint = "https://sor2.sum.dsdn.dk/#id=953741000016009"
        destination.receiver.reference = "Organization/a39d4a04-81c8-11ed-a1eb-0242ac120002"
        sender.reference = "Organization/b79a7914-81c8-11ed-a1eb-0242ac120002"
        source.endpoint = "https://sor2.sum.dsdn.dk/#id=265161000016000"
        focus = "Encounter/d56e9c54-23d2-43a4-816e-951d2a6e3281"
    }
    class "Patient (MedComCorePatient)" as startOnleavePT{
        id = "97404d10-81c8-11ed-a1eb-0242ac120002"
        identifier.system = "urn:oid:1.2.208.176.1.2"
        identifier.value = "2509479989"
        name.use = "official"
        name.family = "Elmer"
        name.given[0] = "Bruno"
        name.given[1] = "Test"
    }
    class "Encounter (MedComHospitalNotificationEncounter)" as startOnleaveENC{
        id = "d56e9c54-23d2-43a4-816e-951d2a6e3281"
        status.system = "http://medcomfhir.dk/ig/terminology/ValueSet/medcom-hospitalNotification-encounterStatus"
        status.code = "onleave"
        class.system = "http://terminology.hl7.org/CodeSystem/v3-ActCode"
        class.code = "IMP"
        subject = "Patient/97404d10-81c8-11ed-a1eb-0242ac120002"
        episodeOfCare.identifier.system = "https://sor2.sum.dsdn.dk/#id=265161000016000"
        episodeOfCare.identifier.value = "bd481c38-a921-11ed-afa1-0242ac120002"
        period.start = "2022-12-07T12:00:00+02:00"
        extension:leavePeriod.start = "2022-12-13T14:00:10+02:00"
        serviceProvider = "Organization/b79a7914-81c8-11ed-a1eb-0242ac120002"
    }    
    class "Receiver (MedComMessagingOrganization)" as startOnleaveROrg{
        id = "a39d4a04-81c8-11ed-a1eb-0242ac120002"
        identifier[0].system = "https://www.gs1.org/gln"
        identifier[0].value = "5790001348120"
        identifier[1].system = "urn:oid:1.2.208.176.1.1"
        identifier[1].value = "953741000016009"
        name = "Plejecenter Herlev"
    }
    class "Sender (MedComMessagingOrganization)" as startOnleaveSOrg{
        id = "b79a7914-81c8-11ed-a1eb-0242ac120002"
        identifier[0].system = "https://www.gs1.org/gln"
        identifier[0].value = "5790000209354"
        identifier[1].system = "urn:oid:1.2.208.176.1.1"
        identifier[1].value = "265161000016000"
        name = "Hjerteafdelingen på Herlev og Gentofte hospital" 
    }
    class "Provenance  (MedComMessagingProvenance)" as admitPRO{
        id = "a7cf3888-6f42-4e4d-929c-d2475d24fba0"
        target = "MessageHeader/b9b4818e-02de-4cc4-b418-d20cbc7b5404"
        occuredDateTime = "2022-12-07T12:00:02+02:00"
        recorded = "2022-12-07T12:00:02+02:00"
        activity.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-activityCodes"
        activity.code = "admit-inpatient"
        agent.who = "Organization/o7056980-a8b2-42aa-8a0e-c1fc85d1f40d"
    }
    class "Provenance  (MedComMessagingProvenance)" as startOnleavePRO{
        id = "dc421d0a-cded-470f-9a53-2ddba7583baa"
        target = "MessageHeader/e563a2b2-bf92-4b13-bbd2-0a021a95bded"
        occuredDateTime = "2022-12-13T14:00:12+02:00"
        recorded = "2022-12-13T14:00:12+02:00"
        activity.system = "http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-activityCodes"
        activity.code = "start-leave-inpatient"
        agent.who = "Organization/b79a7914-81c8-11ed-a1eb-0242ac120002"
        entity.role.system = "http://hl7.org/fhir/ValueSet/provenance-entity-role"
        entity.role.value = "revision"
        entity.what = "MessageHeader/b9b4818e-02de-4cc4-b418-d20cbc7b5404"
    }
startOnleaveB -[hidden]- startOnleaveMH
startOnleaveMH-[hidden]-startOnleavePT
startOnleavePT-[hidden]-startOnleaveENC
startOnleaveENC-[hidden]-startOnleaveROrg
startOnleaveROrg-[hidden]-startOnleaveSOrg
startOnleaveSOrg-[hidden]-admitPRO
admitPRO-[hidden]-startOnleavePRO

}



@enduml

