@startuml HNAdmitInPat

'layout
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
  }
hide circle
hide empty members
skinparam SameClassWidth true
skinparam Ranksep 10

'Message 1: Admit inpatient
package "Message 1: Admit Inpatient" as admit <<Frame>>{
    class "Bundle (MedComHospitalNotificationMessage)" as admitB{
        id = 148a14dd-9614-4445-a136-428ec198df8c
        type = "message"
        timestamp = 2022-09-01T12:00:10+02:00
    }
    class "MessageHeader (MedComHospitalNotificationMessageHeader)" as admitMH{
        id = e422436e-9885-48c4-920d-f7bc05c18aaf
        event = "hospital-notification-message"
        destination:primary = Organization
        destination:primary.use = "primary"
        destination:primary.endpoint = https://sor2.sum.dsdn.dk/#id=953741000016009
        sender =Organization
        source.endpoint = https://sor2.sum.dsdn.dk/#id=265161000016000
        reportOfAdmissionFlag = "true"
        reportofAdmissionRecipient = Organization
        focus = Encounter
    }
    class "Patient (MedComCorePatient)" as admitPT{
        id = d760c244-fc96-44bf-86aa-acbcb7a2797b
        identifier:cpr = 2509479989
        name.family = Elmer
        name.given[0] = Bruno
        name.given[1] = Test
    }
    class "Encounter (MedComHospitalNotificationEncounter)" as admitENC{
        id = 774ab50d-e10d-4c0c-b19c-e9ec8c07e8c9
        status = "in-progress"
        class = "IMP"
        subject = Patient
        episodeOfCare.identifier = "urn:uuid:fc60e762-b13b-5773-865e-67f3907bdcc7"
        period.start = 2022-09-01T12:00:05+02:00
        serviceProvider = Organization
    }    
    class "ServiceProvider Organization (MedComCoreOrganization)" as admitSPOrg{
        id = 774a3d07-e270-4df2-9d2e-2ec99f18dce1
        sorIdentifier = 265161000016000
    }
    class "Receiver: Municipality (MedComMessagingOrganization)" as admitROrg{
        id = 85b7fb3b-510c-43a3-8ef8-18fe22adaafd
        eanIdentifier = 5790001348120
        sorIdentifier = 953741000016009
    }
    class "Sender: Hospital (MedComMessagingOrganization)" as admitSOrg{
        id = 4120546a-44aa-4262-8542-398b2315e9cc
        eanIdentifier = 5790000209354
        sorIdentifier = 265161000016000
    }
    class "Provenance  (MedComMessagingProvenance)" as admitPRO{
        id = a7128eb7-8df1-4479-b56f-9c66970159f6
        target = MessageHeader
        occuredDateTime = 2022-09-01T12:00:30+02:00
        recorded = 2022-09-01T12:00:30
        activity.code = "admit-inpatient"
        agent.who = Organization
    }

admitB -[hidden]- admitMH
admitMH-[hidden]-admitPT
admitPT-[hidden]-admitENC
admitENC-[hidden]-admitSPOrg
admitSPOrg-[hidden]-admitROrg
admitROrg-[hidden]-admitSOrg
admitSOrg-[hidden]-admitPRO
}


@enduml